---
environment:
  masters: 
    - master1.example.com
  nodes: 
    - node1.example.com
    - node2.example.com
    - node3.example.com
  etcds: 
    - etcd1.example.com
  routers: 
    - 
  authtype: htpasswd
  htpasswd: /etc/origin/htpasswd
  subdomain: 
  pbenchserver: pbench.example.com
  monitoring:
    - pbench
    - cloudwatch
exection:
  gituser: vikaslaad
  templates: 
    - django-psql-example
    - nodejs-mongodb-example
    - cakephp-mysql-example
    - dancer-mysql-example
    - rails-postgresql-example
    - eap64-mysql-s2i
  userprefix: u
  loadproject: true
schedule:
  minute: 1
  hour: 2
  day: 10
  week: 20
  month: 40
