provider: local
ClusterLoader:
  cleanup: true
  projects:
    - num: 1
      basename: clusterproject
      tuning: default
      ifexists: delete
      pods:
        - num: 1000
          image: gcr.io/google_containers/pause-amd64:3.0
          basename: pausepods
          file: pod-pause-labeled-nodes.json
  tuningsets:
    - name: default
      pods:
        stepping:
          stepsize: 50
          pause: 60
        ratelimit:
          delay: 0
