apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-{{.Replica}}-{{.Iteration}}
  labels:
    app: pause-{{.Replica}}-{{.Iteration}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause-{{.Replica}}-{{.Iteration}}
  template:
    metadata:
      labels:
        app: pause-{{.Replica}}-{{.Iteration}}
    spec:
      containers:
      - name: pause
        image: gcr.io/google-containers/pause-amd64:3.0
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      