---
- name: install collectd
  yum: name={{ item }} state=latest
  with_items:
    - collectd

- name: Configure collectd.conf
  template:
    src={{config_type}}.collectd.conf.j2
    dest=/etc/collectd.conf
    owner=root
    group=root
    mode=0644
  become: true

- name: allow collectd to use the network
  shell: setsebool -P collectd_tcp_network_connect on

- name: restart collectd service
  service: name=collectd state=stopped
