---
tmp_dir: "/run/"
base_image_location: "{{ tmp_dir }}{{ base_image_filename }}" 
tmp_img_location: "{{ tmp_dir }}osptmp1.{{ qemu_img_format }}"
qemu_img_format: "raw"
qemu_img_location: "{{ tmp_dir }}{{ ansible_date_time.date }}-ocp-{{ openshift_version }}-gold.{{ qemu_img_format }}"
ssh_pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA57NxnEo8KnrBYRrWjgS8eSZBKiUFBbP4GGbC1M1Kxo+494T2+y3uuihK0Ey5n824ch2OafK7m/TnByIC9pQ3VuAi/ggiOfja2gvZ/GtTedE3ct0jVbGbM/98MS0GV1NoIZRqX6e44JMDqID+ngwQutPyTgxbJ/PL2jVUrjP6sOMEJqgSEbQ9a3s+oM3O0vMTLp7E0PtgKQo0bKRoKFEn5mUxiQ2gmwg/dPqOb2/VpBAKCozsE2illszzyP/KC1gq0VkgMqIZspUsXRqvDDbnaSkCc8/AwA0yBAPBMAjtuk5UZvpioHSh2X0ShcgHtYocZiQIxiSvDzvxdYkFBztu6w== perf-team-shared-key"
