---
- hosts: localhost
  user: root
  vars:
    internal_image: false
  roles:
    - { role: repo-install, when: atomic | default(False) | bool }
    - { role: clone-repos, when: atomic | default(False) | bool }

- hosts: all
  user: root
  vars:
    internal_image: false
  roles:
    - { role: delete-oldest, when: target_directory != "" }
    - { role: repo-install, when: not atomic | default(False) | bool }
    - { role: os-kickstart }
    - { role: clone-repos, when: not atomic | default(False) | bool }
    - { role: docker-config }
    - { role: pbench-config, when: not atomic | default(False) | bool}
    - { role: aos-ansible }
    - { role: pbench-kickstart, when: atomic | default(False) | bool }
    - { role: collectd-install }
    - { role: ansible-update, when: not atomic | default(False) | bool }
    - { role: openshift-package-install, when: not atomic | default(False) | bool }
    - { role: seal-image, when: not atomic | default(False) | bool }
    - { role: clean-env, when: atomic | default(False) | bool }
