---
- name: provision gold images
  user: root
  hosts: all
  vars:
    internal_image: true

  roles:
    - repo-install
    - os-kickstart
    - collectd-install
    - clone-repos
    - pbench-config
    - docker-config
    - aos-ansible
    - svt-setup
    - openshift-package-install
    - seal-image

